[package]
name = "_1200_dollars_per_hour"
version = "0.1.3"
license = "MIT"

[addresses]
_1200_dollars_per_hour ="c77384471f05a5d1008d313c3d198d87b0635d8db5673b9e6d735e9a5d6ae35e"
std="0x1"
aptos_framework="0x1"
aptos_std="0x1"
aptos_token="0x3"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies]
AptosStdlib = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir="aptos-move/framework/aptos-stdlib/", rev="dev" }
AptosToken = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir="aptos-move/framework/aptos-token/", rev="dev" }